name: Metrics

on:
  schedule:
    - cron: "0 23 * * *" # every day at midnight UTC
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          user: ${{ github.repository_owner }}
          token: ${{ secrets.METRICS_TOKEN }}

          base: header, activity, community, repositories, metadata

          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: percentage
          plugin_languages_limit: 8

          plugin_isocalendar: yes

          plugin_stars: yes

          plugin_lines: yes

          plugin_followup: yes
